// Firestore Database Schema Documentation
// This document describes the collections and document structure in Firestore

/**
 * COLLECTION: players/{uid}
 * Document structure for authenticated players
 */
export interface PlayerDocument {
  // Basic info
  uid: string;
  email: string;
  displayName?: string;
  createdAt: number; // Timestamp
  
  // Game state
  level: number;
  xp: number;
  xpToNextLevel: number;
  coins: number;
  gems: number;
  energy: number;
  maxEnergy: number;
  lastEnergyRefill: number;
  
  // Inventory
  inventory: Record<string, number>;
  
  // Progression
  lastLogin: number;
  lastSync: number;
  updatedAt: number;
  
  // Analytics
  totalSessionTime: number;
  deviceInfo?: {
    platform: string;
    version: string;
  };
}

/**
 * COLLECTION: farms/{uid}
 * Document structure for farm state
 */
export interface FarmDocument {
  uid: string;
  
  // Crops
  plots: Array<{
    id: string;
    cropId: string;
    plantedAt: number;
    harvestAt: number;
    plotIndex: number;
  }>;
  maxPlots: number;
  
  // Animals
  animals: Array<{
    id: string;
    animalId: string;
    slotIndex: number;
    health: number;
    lastProduction: number;
    nextProduction: number;
    lastFed: number;
  }>;
  maxAnimals: number;
  
  // Buildings
  buildings: Record<string, {
    buildingId: string;
    level: number;
    builtAt: number;
  }>;
  
  // Storage
  storage: Record<string, number>;
  maxStorage: number;
  
  // Upgrades (purchase count for each)
  upgrades: Record<string, number>;
  
  lastSync: number;
  updatedAt: number;
}

/**
 * COLLECTION: marketListings/{itemId}
 * Global marketplace listings (shared across all players)
 * AUTO-UPDATED by Cloud Functions every hour
 */
export interface MarketListingDocument {
  itemName: string;
  basePrice: number;
  currentPrice: number;
  
  // Supply/Demand (0-100 scale)
  supplyLevel: number;
  demandLevel: number;
  
  priceHistory: Array<{
    price: number;
    timestamp: number;
  }>;
  
  lastUpdated: number;
  createdAt: number;
}

/**
 * COLLECTION: contracts/{contractId}
 * Active contracts/quests for players
 * AUTO-GENERATED by Cloud Functions daily
 */
export interface ContractDocument {
  contractId: string;
  uid?: string; // Optional: if player-specific; omitted for public contracts
  
  itemName: string;
  quantity: number;
  reward: number;
  
  createdAt: number;
  dueAt: number; // Deadline timestamp
  completedAt?: number;
  completed: boolean;
  
  // Track who completed if public
  completedBy?: string[];
}

/**
 * COLLECTION: transactions/{transactionId}
 * Audit trail for all economy transactions
 * AUTO-WRITTEN by Cloud Functions
 */
export interface TransactionDocument {
  transactionId: string;
  uid: string;
  
  type: 'sell' | 'buy' | 'craft' | 'build' | 'upgrade' | 'feed' | 'harvest';
  itemName: string;
  quantity: number;
  
  amountCoins?: number;
  amountGems?: number;
  
  balanceBefore: {
    coins: number;
    gems: number;
  };
  balanceAfter: {
    coins: number;
    gems: number;
  };
  
  timestamp: number;
  success: boolean;
}

/**
 * COLLECTION: weatherEvents/{eventId}
 * Current active weather events
 * AUTO-GENERATED by Cloud Functions
 */
export interface WeatherEventDocument {
  eventId: string;
  
  type: 'drought' | 'rain' | 'pest';
  modifier: number; // 0.5 (drought), 1.5 (rain), 0.3 (pest)
  description: string;
  
  startTime: number;
  endTime: number;
  
  affectedPlayers?: string[]; // For targeted events
}

/**
 * COLLECTION: leaderboards/{leaderboardId}
 * Periodic snapshots of top players
 * AUTO-GENERATED by Cloud Functions
 */
export interface LeaderboardDocument {
  leaderboardId: string;
  type: 'level' | 'wealth' | 'xp' | 'trades';
  
  entries: Array<{
    rank: number;
    uid: string;
    displayName: string;
    value: number;
  }>;
  
  generatedAt: number;
  validUntil: number;
}

/**
 * COLLECTION: analyticsEvents/{eventId}
 * Track important game events for analytics
 */
export interface AnalyticsEventDocument {
  eventId: string;
  uid: string;
  
  eventType: string;
  eventData: Record<string, any>;
  
  timestamp: number;
}

// Firestore Indexes Required:
// 1. marketListings: Composite index on (lastUpdated, currentPrice)
// 2. contracts: Composite index on (dueAt, completed)
// 3. leaderboards: Composite index on (type, generatedAt)

// Security Rules:
// - players/{uid}: Only own user can read/write
// - farms/{uid}: Only own user can read/write
// - marketListings: Public read, Server write only (Cloud Functions)
// - contracts: Public read, Server write only
// - transactions: User can read own, Server write only
// - leaderboards: Public read only
